### ISSUE TITLE
Munsell colour chart

### ISSUE THREAD

**Issue by dpk** [pteromys/pteromys.github.io#1]
I found the Munsell colour chart that used to be hosted at http://pteromys.melonisland.net/code/rainbow/munsell.html really useful. It seems to be gone since you moved to GitHub hosting. Is it hosted elsewhere now?

**Comment by pteromys** [comment]
Oh, shoot. I didn't realize anybody was using that! I'll put it back up in like a week. I somehow wrecked my previous hosting in the move and hadn't made time to restore everything. Sorry about that!

**Comment by pteromys** [comment]
It's back! https://github.com/pteromys/munsell/ I'll leave this issue open until I get a chance to add a redirect from the old location too.

**Comment by dpk** [comment]
Awesome, thanks!
